### ISSUE TITLE
Can't build cause from error:"The Assembly UnityEditor is referenced by DOTweenModule.dll"

### ISSUE THREAD

**Issue by teeSngRovn** [lisonghappy/Unity-UIAnimeTool#1]
might cause from the incorrect wrapper of the DOTween plugin

**Comment by teeSngRovn** [comment]
Temporarily solution:
1. delete `3rd` folder,
2. download DOTween release from [here](http://dotween.demigiant.com/download.php)
3. Put downloaded `DOTween` folder into `Assets/Plugins/`

And then finished.
This can temporarily solved this problem without changing any code

**Comment by lisonghappy** [comment]
Thanks for informing!

This bug is caused by my incomplete preprocessing of DOTween, so if you want to solve it, you can simply replace DOTween in the 3rd folder with the official DOTween plugin.
And the issue has been solved.
